trigger:
- main

jobs:

# Build Job
- job: Build
  pool:
    vmImage: 'windows-latest'

  steps:

  - task: UiPathPack@6
    inputs:
      projectJsonPath: '$(Build.SourcesDirectory)'
      versionType: 'AutoVersion'
      outputPath: '$(Build.ArtifactStagingDirectory)\Output'

  - powershell: |
      Get-ChildItem "$(Build.ArtifactStagingDirectory)\Output"
    displayName: 'Verify Package'

  - publish: $(Build.ArtifactStagingDirectory)\Output
    artifact: uipackage


# Approval Job
- job: Approval
  dependsOn: Build
  pool: server

  steps:

  - task: ManualValidation@0
    timeoutInMinutes: 1440
    inputs:
      notifyUsers: 'darshan29sable@gmail.com'
      instructions: |
        Please review the deployment request.

        Approve → Continue deployment
        Reject → Stop deployment

      onTimeout: 'reject'


# Deploy Job
- job: Deploy
  dependsOn: Approval

  pool:
    vmImage: 'windows-latest'

  steps:

  - download: current
    artifact: uipackage

  - task: UiPathDeploy@6
    inputs:
      orchestratorConnection: 'Test'
      packagesPath: '$(Pipeline.Workspace)\uipackage'
      folderName: 'Shared'
      traceLevel: 'Verbose'