trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

# Validate Orchestrator Connection


- task: UiPathPack@6
  inputs:
    projectJsonPath: '$(Build.SourcesDirectory)'
    versionType: 'AutoVersion'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- powershell: |
    Get-ChildItem "$(Build.ArtifactStagingDirectory)\Output"
  displayName: 'Verify Package'

- task: UiPathDeploy@6
  inputs:
    orchestratorConnection: 'Test'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    createProcess: false
    folderName: 'Shared'