trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

# Validate Orchestrator Connection

- powershell: |

    Write-Host "Printing UiPath Connection Details"

    Write-Host "Organization URL:"
    Write-Host "$(uipathOrganizationUrl)"

    Write-Host "Tenant Name:"
    Write-Host "$(uipathTenant)"

  displayName: 'Print UiPath Organization and Tenant'

- task: UiPathPack@6
  inputs:
    projectJsonPath: '$(Build.SourcesDirectory)'
    versionType: 'AutoVersion'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- powershell: |
    Get-ChildItem "$(Build.ArtifactStagingDirectory)\Output"
  displayName: 'Verify Package'

- task: UiPathDeploy@6
  inputs:
    orchestratorConnection: 'Dev'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    createProcess: false
    folderName: 'Shared'